### ISSUE TITLE
Add multiple projects support

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/mkdocs-doxygen-snippets-plugin#1]
Config file:
```yaml
plugins:
    - search
    - doxygen-snippets:
        - rbcx-esp:
            doxygen-path: build/RB3204-RBCX-library/
            doxygen-config: Doxyfile
            doxygen-input: src
            doxygen-output: doc
            api-output: docs/api-esp/
        - rbcx-stm:
            doxygen-path: build/RB3204-RBCX/
            doxygen-config: Doxyfile
            doxygen-input: src
            doxygen-output: doc
            api-output: docs/api-stm/
```
