### ISSUE TITLE
Add source code snippets generator

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/mkdocs-doxygen-snippets-plugin#11]
Example usage:
```yaml
::: doxy.Code
    file: main.cpp
    start: 5  # line
    end: 15 # line
    ...
```
