### ISSUE TITLE
Edit Doxifile through main config

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/mkdocs-doxygen-snippets-plugin#3]
Edit Doxifile through main config

```yaml
plugins:
    - search
    - doxygen-snippets:
        doxyfile:
            - DOXYFILE_ENCODING: UTF-8
            - EXAMPLE_PATH': my_examples
```
