### ISSUE TITLE
Change main plugin config

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/mkdocs-doxygen-snippets-plugin#4]
Add more groups and subgroups

```yaml
plugins:
    - search
    - doxygen-snippets:
        doxygen:
            path: build/RB3204-RBCX-library/
            config: Doxyfile
            input: src
            output: doc
            ...
```
