### ISSUE TITLE
Improve Regex

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/mkdocs-doxygen-snippets-plugin#9]
Improve or simplify Regex

**Comment by JakubAndrysek** [comment]
Add support add tags to headers like in [mkdocstrings](https://mkdocstrings.github.io/usage/#autodoc-syntax).

It is also possible to integrate a mkdocstrings identifier into a Markdown header:
```
## ::: my_package.my_module.MyClass
    options:
      show_source: false
```
The above is equivalent to:


```
::: my_package.my_module.MyClass
    options:
      show_source: false
      heading_level: 2
```
